-- MySQL Script generated by MySQL Workbench
-- Tue Jul  9 01:15:19 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema oc_pizza
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema oc_pizza
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `oc_pizza` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `oc_pizza` ;

-- -----------------------------------------------------
-- Table `oc_pizza`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oc_pizza`.`address` (
  `id_address` BIGINT NOT NULL AUTO_INCREMENT,
  `number_of_street` INT NOT NULL,
  `street` VARCHAR(50) NOT NULL,
  `postal_code` INT NOT NULL,
  `city` VARCHAR(50) NOT NULL,
  `additional_information` VARCHAR(300) NULL DEFAULT NULL,
  PRIMARY KEY (`id_address`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `oc_pizza`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oc_pizza`.`customer` (
  `id_customer` BIGINT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(50) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `date_of_birth` DATE NOT NULL,
  `phone_number` VARCHAR(15) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `client_picture` VARCHAR(300) NULL DEFAULT NULL,
  `account_name` VARCHAR(100) NOT NULL,
  `account_password` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_customer`),
  UNIQUE INDEX `phone_number` (`phone_number` ASC) VISIBLE,
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  UNIQUE INDEX `account_name` (`account_name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `oc_pizza`.`command_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oc_pizza`.`command_status` (
  `id_command_status` BIGINT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_command_status`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `oc_pizza`.`payment_method`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oc_pizza`.`payment_method` (
  `id_payment_method` BIGINT NOT NULL AUTO_INCREMENT,
  `method` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_payment_method`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `oc_pizza`.`payment_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oc_pizza`.`payment_status` (
  `id_payment_status` BIGINT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_payment_status`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `oc_pizza`.`employe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oc_pizza`.`employe` (
  `id_employe` BIGINT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(50) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `phone_number` VARCHAR(15) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `date_of_birth` DATE NOT NULL,
  `fonction` VARCHAR(20) NOT NULL,
  `id_sales_point` BIGINT NOT NULL,
  PRIMARY KEY (`id_employe`),
  UNIQUE INDEX `phone_number` (`phone_number` ASC) VISIBLE,
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `oc_pizza`.`command`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oc_pizza`.`command` (
  `id_command` BIGINT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `delivery_hours` INT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `payment_amount` FLOAT NULL DEFAULT NULL,
  `id_customer` BIGINT NOT NULL,
  `id_command_status` BIGINT NOT NULL,
  `id_payment_status` BIGINT NOT NULL,
  `id_payment_method` BIGINT NOT NULL,
  `id_command_maker` BIGINT NOT NULL,
  `id_delivery_man` BIGINT NOT NULL,
  PRIMARY KEY (`id_command`),
  INDEX `id_customer` (`id_customer` ASC) VISIBLE,
  INDEX `id_command_status` (`id_command_status` ASC) VISIBLE,
  INDEX `id_payment_method` (`id_payment_method` ASC) VISIBLE,
  INDEX `id_payment_status` (`id_payment_status` ASC) VISIBLE,
  INDEX `fk_command_maker` (`id_command_maker` ASC) VISIBLE,
  INDEX `fk_delivery_man` (`id_delivery_man` ASC) VISIBLE,
  CONSTRAINT `command_ibfk_1`
    FOREIGN KEY (`id_customer`)
    REFERENCES `oc_pizza`.`customer` (`id_customer`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `command_ibfk_2`
    FOREIGN KEY (`id_command_status`)
    REFERENCES `oc_pizza`.`command_status` (`id_command_status`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `command_ibfk_3`
    FOREIGN KEY (`id_payment_method`)
    REFERENCES `oc_pizza`.`payment_method` (`id_payment_method`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `command_ibfk_4`
    FOREIGN KEY (`id_payment_status`)
    REFERENCES `oc_pizza`.`payment_status` (`id_payment_status`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_command_maker`
    FOREIGN KEY (`id_command_maker`)
    REFERENCES `oc_pizza`.`employe` (`id_employe`),
  CONSTRAINT `fk_delivery_man`
    FOREIGN KEY (`id_delivery_man`)
    REFERENCES `oc_pizza`.`employe` (`id_employe`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `oc_pizza`.`command_maker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oc_pizza`.`command_maker` (
  `id_employe` BIGINT NOT NULL,
  PRIMARY KEY (`id_employe`),
  CONSTRAINT `command_maker_ibfk_1`
    FOREIGN KEY (`id_employe`)
    REFERENCES `oc_pizza`.`employe` (`id_employe`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `oc_pizza`.`pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oc_pizza`.`pizza` (
  `id_pizza` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `picture` VARCHAR(100) NULL DEFAULT NULL,
  `selling_price` FLOAT NOT NULL,
  `receipt` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id_pizza`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE,
  UNIQUE INDEX `receipt` (`receipt` ASC) VISIBLE,
  UNIQUE INDEX `picture` (`picture` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `oc_pizza`.`command_pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oc_pizza`.`command_pizza` (
  `id_command` BIGINT NOT NULL,
  `id_pizza` BIGINT NOT NULL,
  `quantity_same_pizza` INT NOT NULL DEFAULT '1',
  PRIMARY KEY (`id_command`, `id_pizza`),
  INDEX `id_pizza` (`id_pizza` ASC) VISIBLE,
  CONSTRAINT `command_pizza_ibfk_1`
    FOREIGN KEY (`id_command`)
    REFERENCES `oc_pizza`.`command` (`id_command`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `command_pizza_ibfk_2`
    FOREIGN KEY (`id_pizza`)
    REFERENCES `oc_pizza`.`pizza` (`id_pizza`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `oc_pizza`.`customer_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oc_pizza`.`customer_address` (
  `id_customer` BIGINT NOT NULL,
  `id_address` BIGINT NOT NULL,
  PRIMARY KEY (`id_customer`, `id_address`),
  INDEX `id_address` (`id_address` ASC) VISIBLE,
  CONSTRAINT `customer_address_ibfk_1`
    FOREIGN KEY (`id_customer`)
    REFERENCES `oc_pizza`.`customer` (`id_customer`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `customer_address_ibfk_2`
    FOREIGN KEY (`id_address`)
    REFERENCES `oc_pizza`.`address` (`id_address`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `oc_pizza`.`delivery_man`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oc_pizza`.`delivery_man` (
  `id_employe` BIGINT NOT NULL,
  PRIMARY KEY (`id_employe`),
  CONSTRAINT `delivery_man_ibfk_1`
    FOREIGN KEY (`id_employe`)
    REFERENCES `oc_pizza`.`employe` (`id_employe`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `oc_pizza`.`ingredient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oc_pizza`.`ingredient` (
  `id_ingredient` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_ingredient`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `oc_pizza`.`pizza_ingredient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oc_pizza`.`pizza_ingredient` (
  `id_pizza` BIGINT NOT NULL,
  `id_ingredient` BIGINT NOT NULL,
  PRIMARY KEY (`id_pizza`, `id_ingredient`),
  INDEX `id_ingredient` (`id_ingredient` ASC) VISIBLE,
  CONSTRAINT `pizza_ingredient_ibfk_1`
    FOREIGN KEY (`id_pizza`)
    REFERENCES `oc_pizza`.`pizza` (`id_pizza`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `pizza_ingredient_ibfk_2`
    FOREIGN KEY (`id_ingredient`)
    REFERENCES `oc_pizza`.`ingredient` (`id_ingredient`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `oc_pizza`.`sales_point`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oc_pizza`.`sales_point` (
  `id_sales_point` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `is_open` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id_sales_point`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `oc_pizza`.`unity_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oc_pizza`.`unity_type` (
  `id_unity_type` BIGINT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`id_unity_type`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `oc_pizza`.`unity_quantity_stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oc_pizza`.`unity_quantity_stock` (
  `id_sales_point` BIGINT NOT NULL,
  `id_ingredient` BIGINT NOT NULL,
  `id_unity_type` BIGINT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `amount` FLOAT NULL DEFAULT NULL,
  `limit_quantity` TINYINT(1) NULL DEFAULT '0',
  `purchasing_price_per_unit` FLOAT NOT NULL,
  PRIMARY KEY (`id_sales_point`, `id_ingredient`),
  INDEX `id_ingredient` (`id_ingredient` ASC) VISIBLE,
  INDEX `id_unity_type` (`id_unity_type` ASC) VISIBLE,
  CONSTRAINT `unity_quantity_stock_ibfk_1`
    FOREIGN KEY (`id_sales_point`)
    REFERENCES `oc_pizza`.`sales_point` (`id_sales_point`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `unity_quantity_stock_ibfk_2`
    FOREIGN KEY (`id_ingredient`)
    REFERENCES `oc_pizza`.`ingredient` (`id_ingredient`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `unity_quantity_stock_ibfk_4`
    FOREIGN KEY (`id_unity_type`)
    REFERENCES `oc_pizza`.`unity_type` (`id_unity_type`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;